version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: rustuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rust_api
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    environment:
      - DATABASE_URL=postgres://rustuser:password@db:5432/rust_api
      - JWT_SECRET=my_super_secret_key
    depends_on:
      - db
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - backend
      - frontend

volumes:
  db_data:
